### ISSUE TITLE
An obsolete version of sbt in build.properties file

### ISSUE THREAD

**Issue by tetianaYer** [rockthejvm/advanced-scala#2]
I noticed that the project used sbt.version=1.5.2 which is very old and causes issues if using java version >17 (I use 22 and cannot build project)
<img width="1522" alt="Screenshot 2024-08-16 at 14 15 29" src="https://github.com/user-attachments/assets/0ee81372-6ebb-409f-af47-5b464714763a">

**Comment by daniel-ciocirlan** [comment]
Bumped SBT - thanks!
